---
# tasks file for ansible-role-httpd

- assert:
    that:
      - "ansible_os_family == 'OpenBSD'"

- name: Create httpd.conf
  template:
    src: httpd.conf.j2
    dest: "{{ httpd_conf_file }}"
  notify: Restart httpd

- name: Start httpd
  service:
    name: "{{ httpd_service }}"
    enabled: true
    state: started
